"""Codegen: config/tables.json -> one Liquibase changelog file PER table.

Why a generator instead of one shared changelog
------------------------------------------------
The earlier Liquibase path ran a SINGLE shared changelog (`changelog/db.changelog-master.xml`)
once per table, passing per-table values as Liquibase properties (`-Dsynced_table=…`,
`-Dapp_role=…`, `-Dindex_col_1/2=…`). Liquibase keys a changeset by (FILENAME, id, author) and
folds the substituted property values into the changeset checksum. So two tables in the SAME
`app_schema` shared ONE `DATABASECHANGELOG`, and the second table tripped
`ValidationFailedException` on `001-app-role` (same FILENAME+id+author as the first table, but a
different checksum) — its role and grants were never created. Verified against a live Lakebase instance.

That same shared changelog also forced the index step through a fixed TWO-slot template
(`${index_col_1}`/`${index_col_2}`), silently capping `index_columns` at 2.

The fix (this module), mirroring `dabs/generate_resources.py` (same single source of truth,
ADR 0004): read `config/tables.json` and write ONE Liquibase formatted-SQL changelog per row to
`liquibase/generated/<name>.changelog.sql`, with every value BAKED IN (no `${…}` properties):

  * a per-table FILE => a UNIQUE changeset identity (distinct FILENAME) even when tables share a
    schema and one DATABASECHANGELOG => no cross-table checksum collision;
  * N index changesets straight from `index_columns` (0/1/N) => no two-column cap;
  * changesets stay idempotent + runAlways, so a synced-table replace reapplies grants/indexes/view.

The generated changelogs are CHECKED INTO the repo; `--check` is a byte-for-byte drift guard
(same pattern as `dabs/generate_resources.py --check` / `offline_validate.sh`), wired into the
offline CI gate. `scripts/deploy.sh` runs `liquibase update --changeLogFile=generated/<name>...`
once per table.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

# The four idempotent SQL builders + the identifier seam live in ONE place, `dabs/render_ddl.py`,
# and BOTH migration paths consume them (single source of the idempotent SQL). The DABs renderer
# emits them as a plain SQL blob; this generator wraps the same statements in Liquibase changesets.
# Put the repo root on sys.path so this resolves whether the module is run as a script
# (`python liquibase/generate_changelogs.py`), imported by tests, or invoked in CI — __file__ is
# always bound here (this module is never exec'd headless like the serverless job entrypoint).
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
from dabs.render_ddl import (  # noqa: E402  (path insertion must precede this import)
    grant_statements,
    index_statements,
    load_tables,
    pg_table_name,
    resolve_view_name,
    role_guard_sql,
    validate_identifier,
    validate_view_names_unique,
    view_statements,
)

# logicalFilePath: Liquibase records a changeset's identity partly from the changelog
# FILENAME, which it resolves relative to cwd / --search-path. deploy.sh runs liquibase from
# `liquibase/` (so the filename is `generated/<name>.changelog.sql`) while CI may run from repo-root
# with a --search-path — the SAME changelog would then be recorded under DIFFERENT filenames, giving
# it DIFFERENT identities, so an operator running from a different cwd re-executes changesets already
# applied (or hits a validation mismatch). Declaring `logicalFilePath:generated/<name>.changelog.sql`
# in the formatted-SQL header pins the recorded DATABASECHANGELOG.filename to a stable, cwd-independent
# value in BOTH cases.
_LOGICAL_PATH_DIR = "generated"


def _generated_header(logical_path: str) -> str:
    """The formatted-SQL header for one changelog, with a cwd-independent logicalFilePath."""
    return (
        f"--liquibase formatted sql logicalFilePath:{logical_path}\n"
        "-- GENERATED by liquibase/generate_changelogs.py from config/tables.json — DO NOT EDIT BY HAND.\n"
        "-- Re-run the generator after editing config/tables.json (single source of truth, ADR 0004).\n"
        "-- One changelog per table => a unique changeset identity per table (distinct FILENAME), so\n"
        "-- tables that share an app_schema never collide in one DATABASECHANGELOG.\n"
        "-- logicalFilePath pins the recorded filename so identity is stable regardless of cwd\n"
        "-- (deploy.sh runs from liquibase/, CI may run from repo-root with --search-path).\n"
    )


# `load_tables`, `validate_identifier`, and `pg_table_name` are imported from dabs.render_ddl (the
# single home shared with the DABs path); they remain part of this module's public surface via that
# import. `load_tables` lives in one place so both engines read config identically.


def changelog_filename(table: dict) -> str:
    """The changelog file name for a table row (its `name` is the unique per-table handle)."""
    return f"{validate_identifier(table['name'], 'name')}.changelog.sql"


def logical_file_path(table: dict) -> str:
    """The cwd-independent Liquibase logicalFilePath for a table's changelog.

    Always `generated/<name>.changelog.sql`, matching the path deploy.sh passes to
    `--changeLogFile` from the `liquibase/` directory — so the recorded DATABASECHANGELOG.filename
    is the same whether liquibase runs from `liquibase/` or from repo-root with a --search-path."""
    return f"{_LOGICAL_PATH_DIR}/{changelog_filename(table)}"


@dataclass
class Changeset:
    """One Liquibase changeset: (author, id) plus its formatted-SQL body and attributes."""

    author: str
    id: str
    attrs: str  # e.g. "runAlways:true" or "runOnChange:false splitStatements:false"
    comment: str
    sql: str
    rollback: list[str] = field(default_factory=list)

    def render(self) -> str:
        head = f"--changeset {self.author}:{self.id}"
        if self.attrs:
            head += f" {self.attrs}"
        lines = [head]
        lines += [f"-- {c}" for c in self.comment.splitlines()]
        lines.append(self.sql.rstrip("\n"))
        lines += [f"--rollback {r}" for r in self.rollback]
        return "\n".join(lines) + "\n"


def _one_statement(stmt: str) -> str:
    """Terminate a single builder statement for a Liquibase changeset body."""
    return stmt + ";"


def _joined_statements(stmts: list[str]) -> str:
    """Join a builder's statement list into one changeset body, each statement terminated."""
    return ";\n".join(stmts) + ";"


def build_changesets(table: dict) -> list[Changeset]:
    """The ordered changesets for one table: role -> grants -> N indexes -> consumer view.

    The SQL for each changeset comes from the SHARED builders in `dabs/render_ddl.py`
    (`role_guard_sql` / `grant_statements` / `index_statements` / `view_statements`), so the
    Liquibase and DABs paths emit the SAME idempotent DDL from ONE definition — this generator only
    wraps those statements in changeset headers (id, author, runAlways/rollback). Values are baked
    (validated) per table — role, schema, pg-table name and each index column. Ordering: role, then
    explicit grants, then indexes (run after the initial sync loads data), then the no-superuser
    consumer view + its grant.
    """
    role = validate_identifier(table["app_role"], "app_role")
    schema = validate_identifier(table["app_schema"], "app_schema")
    tbl = validate_identifier(pg_table_name(table), "synced_table")
    index_columns = [validate_identifier(c, "index_column") for c in (table.get("index_columns") or [])]
    view = resolve_view_name(table, tbl)  # config `view_name` override, else derived <tbl>_v

    changesets: list[Changeset] = []

    # 001 — app role. Guarded so a fresh instance rebuild is safe. splitStatements:false: the DO
    # block has internal semicolons and must be sent as ONE statement. runOnChange:true here:
    # Liquibase folds this formatted-SQL body — INCLUDING its `-- ` comment lines — into the
    # changeset checksum, so any future reword of role_guard_sql or these comments would flip the
    # checksum and fail validation on every EXISTING deploy under the default runOnChange:false.
    # The guard is idempotent (pg_roles existence check around CREATE ROLE), so re-running on a
    # body change is safe.
    changesets.append(
        Changeset(
            author="cicd",
            id="001-app-role",
            attrs="runOnChange:true splitStatements:false",
            comment=(
                "App-specific read-only role. Idempotent (guarded) so a fresh rebuild is safe.\n"
                "runOnChange:true: the guard body is part of the Liquibase checksum, so a reword\n"
                "must re-run (idempotent), not fail validation on existing deploys."
            ),
            sql=_one_statement(role_guard_sql(role)),
            rollback=[f"DROP ROLE IF EXISTS {role};"],
        )
    )

    # 002 — explicit native grants. runAlways so they are reapplied after a synced-table
    # create/replace (a sync-mode change forces destroy+recreate, dropping grants). GRANT is
    # idempotent, so reapplying is a no-op on a normal deploy.
    changesets.append(
        Changeset(
            author="cicd",
            id="002-app-grants",
            attrs="runAlways:true",
            comment=(
                "Schema USAGE only (least privilege), reapplied after each synced-table create/replace.\n"
                "No base-table SELECT: the app role reads only through the 004 consumer view.\n"
                "runAlways (not runOnChange): GRANT is idempotent; a replace drops grants otherwise."
            ),
            sql=_joined_statements(grant_statements(schema, role, tbl)),
            rollback=[
                f"REVOKE USAGE ON SCHEMA {schema} FROM {role};",
            ],
        )
    )

    # 003 — one index changeset PER index column (0/1/N). No two-slot cap: a table with three index
    # columns gets three changesets. CREATE INDEX IF NOT EXISTS + runAlways => idempotent no-op on a
    # normal deploy, rebuilt after a table replace.
    for col in index_columns:
        changesets.append(
            Changeset(
                author="cicd",
                id=f"003-index-{col}",
                attrs="runAlways:true",
                comment=(
                    "Applied after the initial load. CREATE INDEX IF NOT EXISTS + runAlways =>\n"
                    "idempotent no-op normally, rebuilt after a synced-table replace."
                ),
                sql=_one_statement(index_statements(schema, tbl, [col])[0]),
                rollback=[f"DROP INDEX IF EXISTS {schema}.idx_{tbl}_{col};"],
            )
        )

    # 004 — no-superuser consumer view + grant. The managed writer role owns the synced base table;
    # the deploy identity holds SELECT on that base table and OWNS this view over it, so it can grant
    # consumers SELECT on the VIEW — no databricks_superuser or writer role membership needed.
    # runAlways so the view + grants survive a synced-table replace.
    changesets.append(
        Changeset(
            author="cicd",
            id="004-app-view",
            attrs="runAlways:true",
            comment=(
                "No-superuser consumer pattern: the deploy identity owns this view over the synced\n"
                "table and grants consumers SELECT on the VIEW. runAlways so it survives a replace."
            ),
            sql=_joined_statements(view_statements(schema, role, tbl, view)),
            rollback=[f"DROP VIEW IF EXISTS {schema}.{view};"],
        )
    )

    return changesets


def changeset_identities(table: dict) -> list[tuple[str, str, str]]:
    """The (FILENAME, author, id) identity of every changeset for a table — mirrors how Liquibase
    keys DATABASECHANGELOG rows. The FILENAME (the per-table changelog file) is what makes an
    identical (author, id) pair distinct across tables that share a schema."""
    fname = changelog_filename(table)
    return [(fname, cs.author, cs.id) for cs in build_changesets(table)]


def render_changelog(table: dict) -> str:
    """Render one table's full formatted-SQL changelog (header + ordered changesets)."""
    body = "\n".join(cs.render() for cs in build_changesets(table))
    return _generated_header(logical_file_path(table)) + "\n" + body


def write_changelogs(tables: list[dict], out_dir: str | Path) -> list[Path]:
    """Generate and write one changelog file per table to `out_dir`. Returns the paths written.

    Fully deterministic (no timestamps/ids) so re-running is a clean diff.
    """
    validate_view_names_unique(tables)  # cross-entry: two entries must not resolve to one view
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for table in tables:
        path = out / changelog_filename(table)
        path.write_text(render_changelog(table))
        written.append(path)
    return written


def check_drift(config_path: str | Path, generated_dir: str | Path) -> list[str]:
    """Verify committed changelogs in `generated_dir` byte-match a FRESH generation from
    `config_path`. Returns human-readable drift descriptions; empty list == no drift. Writes nothing.

    Reports all three ways a committed tree can diverge from the single source of truth:
      - a committed file whose bytes differ from the freshly generated content (stale/hand-edited),
      - an expected file missing from the committed tree,
      - a committed .changelog.sql that no config row generates (orphan/leftover).
    """
    tables = load_tables(config_path)
    validate_view_names_unique(tables)  # cross-entry: two entries must not resolve to one view
    expected = {changelog_filename(t): render_changelog(t) for t in tables}
    generated = Path(generated_dir)
    committed = {p.name: p for p in generated.glob("*.changelog.sql")}

    problems: list[str] = []
    for fn, content in expected.items():
        if fn not in committed:
            problems.append(f"missing committed changelog: {fn} (expected from config, not present)")
        elif committed[fn].read_text() != content:
            problems.append(f"drift in {fn}: committed bytes differ from fresh generation")
    for fn in committed:
        if fn not in expected:
            problems.append(f"unexpected committed changelog: {fn} (no config row generates it)")
    return problems


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--config",
        default=str(repo_root / "config" / "tables.json"),
        help="Path to the single-source-of-truth tables.json (default: repo config/tables.json).",
    )
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent / "generated"),
        help="Output directory for generated changelogs (default: liquibase/generated).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify-only: confirm the committed changelogs in --out byte-match a fresh generation "
             "from --config, exit non-zero on any drift. Writes nothing (for CI / the offline gate).",
    )
    args = parser.parse_args(argv)

    if args.check:
        problems = check_drift(args.config, args.out)
        if problems:
            for p in problems:
                print(f"DRIFT: {p}", file=sys.stderr)
            print(
                f"ERROR: committed changelogs in {args.out} are stale vs {args.config} "
                f"({len(problems)} issue(s)). Re-run codegen and commit liquibase/generated/*.changelog.sql.",
                file=sys.stderr,
            )
            return 1
        print(f"no drift: committed changelogs in {args.out} match a fresh generation from {args.config}")
        return 0

    tables = load_tables(args.config)
    written = write_changelogs(tables, args.out)
    for path in written:
        print(f"wrote {path}")
    print(f"generated {len(written)} changelog(s) for {len(tables)} table(s) from {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
