"""Codegen: config/tables.json -> Databricks Asset Bundle resource YAML (ticket 01).

The DABs path is driven by the SAME single source of truth as Terraform's `for_each` and the
deploy loop (ADR 0004): the repo-root `config/tables.json`. DABs YAML cannot loop a JSON list
into N resources, so this generator emits, per table, one `postgres_synced_tables` and one
`postgres_roles` resource — a transparent, diffable artifact rather than a hidden mutator
(ADR 0006 / D2/D3). Adding a table stays a one-line `config/tables.json` edit.

Schema mapping (field names verified against `databricks bundle schema`, CLI v1.14.1):

  config/tables.json field    -> bundle location
  --------------------------      -----------------
  name                        -> synced-table resource key <name>; role resource key <name>_role
                                 (resource keys share one namespace, so the role cannot reuse <name>)
  synced_table_id             -> postgres_synced_tables.<name>.synced_table_id   (required)
                                 postgres_synced_tables.<name>.new_pipeline_spec.storage_catalog
                                   (DERIVED: 1st dotted part of synced_table_id)
                                 postgres_synced_tables.<name>.new_pipeline_spec.storage_schema
                                   (DERIVED: 2nd dotted part of synced_table_id)
  source_table_full_name      -> postgres_synced_tables.<name>.source_table_full_name
  primary_key_columns         -> postgres_synced_tables.<name>.primary_key_columns
  scheduling_policy (optional)-> postgres_synced_tables.<name>.scheduling_policy
                                 (default SNAPSHOT; enum CONTINUOUS|TRIGGERED|SNAPSHOT). The
                                 synced-table CREATE API rejects a missing policy, so it always emits.
  app_role                    -> postgres_roles.<name>_role.postgres_role  (the PG role name)
                                 postgres_roles.<name>_role.role_id        (RFC-1123 slug of app_role)
  app_schema, index_columns   -> variables.migration_targets.default[]  (see note)

Both `postgres_synced_tables` and `postgres_roles` declare `additionalProperties: false` in the
bundle schema, so there is NO native resource field for a synced table's index columns or its
target schema. Those are consumed by the Alembic migration job (which applies the indexes and the
consumer view), so they are carried as a bundle `variables` complex default (`migration_targets`)
— a bundle-legal location that `databricks bundle validate` accepts and the job task can read.
This keeps index columns "carried through" in full (no fixed-count truncation) without inventing
a resource field that the CLI would reject.

Environment-specific placement is left as bundle variable references so no customer/workspace-specific
value is committed: the role's `parent` (the Lakebase branch it lives on) uses `${var.lakebase_branch}`,
the synced table's `postgres_database` uses `${var.lakebase_database}`, and the synced table's `branch`
also uses `${var.lakebase_branch}` — the SAME var the role's `parent` uses, so a target sets the branch
once and both the synced table and its role follow it onto the same Lakebase branch (dev/prod placement
stays separated, and an ephemeral-branch test can isolate). Those variables are declared in the bundle's
`databricks.yml` targets (ticket 02).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

# Bundle variable references for environment-specific values (declared in databricks.yml targets).
# Kept as references — never literal workspace/branch values — so nothing customer-specific is committed.
BRANCH_VAR = "${var.lakebase_branch}"
DATABASE_VAR = "${var.lakebase_database}"

# Scheduling policy for a synced table's underlying pipeline. Enum verified against
# `databricks bundle schema`, CLI v1.14.1
# (postgres.SyncedTableSyncedTableSpecSyncedTableSchedulingPolicy).
VALID_SCHEDULING_POLICIES = ("CONTINUOUS", "TRIGGERED", "SNAPSHOT")
DEFAULT_SCHEDULING_POLICY = "SNAPSHOT"

_GENERATED_HEADER = (
    "# GENERATED by dabs/generate_resources.py from config/tables.json — DO NOT EDIT BY HAND.\n"
    "# Re-run the generator after editing config/tables.json (single source of truth, ADR 0004).\n"
)


def load_tables(config_path: str | Path) -> list[dict]:
    """Read the single-source-of-truth tables config as a list of dicts."""
    with Path(config_path).open() as fh:
        tables = json.load(fh)
    if not isinstance(tables, list):
        raise ValueError(f"{config_path}: expected a JSON array of table objects")
    return tables


def _role_id(app_role: str) -> str:
    """RFC-1123 slug for the role resource id: lowercase, digits and hyphens only.

    The bundle `role_id` must match RFC 1123 (no underscores); the actual Postgres role name
    (`postgres_role`) keeps the config's `app_role` verbatim.
    """
    slug = re.sub(r"[^a-z0-9-]+", "-", app_role.lower()).strip("-")
    return slug or "app-role"


def _scheduling_policy(table: dict) -> str:
    """Resolve the synced table's `scheduling_policy`.

    Defaults to SNAPSHOT; an OPTIONAL `scheduling_policy` field on the config row overrides it
    (backward-compatible: absent -> SNAPSHOT). Rejects any value outside the bundle-schema enum so
    codegen never emits a policy the CLI would refuse. The synced-table CREATE API rejects a
    missing/None policy ('Unsupported scheduling policy: None'), so this field must always emit.
    """
    policy = table.get("scheduling_policy", DEFAULT_SCHEDULING_POLICY)
    if policy not in VALID_SCHEDULING_POLICIES:
        raise ValueError(
            f"scheduling_policy {policy!r} for table {table.get('name')!r} is not one of "
            f"{VALID_SCHEDULING_POLICIES} (bundle-schema enum)"
        )
    return policy


def _new_pipeline_spec(table: dict) -> dict[str, str]:
    """Derive `new_pipeline_spec.storage_catalog` / `storage_schema` from the synced_table_id.

    The pipeline created for the synced table stores its intermediate files (checkpoints, event
    logs) in the synced table's OWN catalog and schema — the 1st and 2nd dotted parts of the
    3-part `catalog.schema.table` identifier — matching the deployed reference Terraform. Sub-field
    names verified against `databricks bundle schema`, CLI v1.14.1 (postgres.NewPipelineSpec):
    storage_catalog, storage_schema.
    """
    parts = table["synced_table_id"].split(".")
    if len(parts) < 3:
        raise ValueError(
            f"synced_table_id {table['synced_table_id']!r} for table {table.get('name')!r} "
            "must be a 3-part catalog.schema.table identifier"
        )
    return {"storage_catalog": parts[0], "storage_schema": parts[1]}


def build_synced_table_resource(table: dict) -> dict[str, Any]:
    """One `postgres_synced_tables` resource body for a table row."""
    return {
        "synced_table_id": table["synced_table_id"],
        "source_table_full_name": table["source_table_full_name"],
        "primary_key_columns": list(table["primary_key_columns"]),
        "postgres_database": DATABASE_VAR,
        "branch": BRANCH_VAR,
        "scheduling_policy": _scheduling_policy(table),
        "new_pipeline_spec": _new_pipeline_spec(table),
        "create_database_objects_if_missing": True,
    }


def build_role_resource(table: dict) -> dict[str, Any]:
    """One `postgres_roles` resource body for a table row (read-only app role)."""
    return {
        "role_id": _role_id(table["app_role"]),
        "postgres_role": table["app_role"],
        "parent": BRANCH_VAR,
    }


def build_migration_target(table: dict) -> dict[str, Any]:
    """Per-table migration metadata the Alembic job consumes (schema + full index column list)."""
    return {
        "name": table["name"],
        "app_schema": table["app_schema"],
        "app_role": table["app_role"],
        "index_columns": list(table["index_columns"]),
    }


def build_bundle_fragments(tables: list[dict]) -> dict[str, dict]:
    """Pure function: tables list -> {filename: bundle-fragment dict}.

    Emits one per-table resource file (`<name>.yml`) carrying that table's synced table and role,
    plus a single `migration_targets.yml` carrying the per-table migration metadata as a bundle
    complex variable. Fully deterministic — no timestamps or ids — so re-running is a clean diff.
    """
    fragments: dict[str, dict] = {}
    targets: list[dict] = []
    for table in tables:
        name = table["name"]
        # DABs resource keys share ONE namespace across all resource types (they are the
        # `${resources.<key>}` reference handles), so the synced table and its role cannot both
        # be keyed `<name>` — the CLI rejects it as a duplicate key. The role gets a distinct
        # `<name>_role` key; the synced table keeps `<name>` as its natural handle.
        fragments[f"{name}.yml"] = {
            "resources": {
                "postgres_synced_tables": {name: build_synced_table_resource(table)},
                "postgres_roles": {f"{name}_role": build_role_resource(table)},
            }
        }
        targets.append(build_migration_target(table))

    fragments["migration_targets.yml"] = {
        "variables": {
            "migration_targets": {
                "type": "complex",
                "description": (
                    "Per-table migration metadata (target schema + index columns) generated from "
                    "config/tables.json and consumed by the Alembic migration job. Index columns "
                    "have no native postgres_synced_tables field, so they are carried here."
                ),
                "default": targets,
            }
        }
    }
    return fragments


def _dump(fragment: dict) -> str:
    """Serialize a bundle fragment to deterministic, block-style YAML with a generated header."""
    body = yaml.safe_dump(fragment, default_flow_style=False, sort_keys=False)
    return _GENERATED_HEADER + body


def write_resources(tables: list[dict], out_dir: str | Path) -> list[Path]:
    """Generate and write all bundle-fragment files to `out_dir`. Returns the paths written."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, fragment in build_bundle_fragments(tables).items():
        path = out / filename
        path.write_text(_dump(fragment))
        written.append(path)
    return written


def check_drift(config_path: str | Path, resources_dir: str | Path) -> list[str]:
    """Verify committed resource files in `resources_dir` byte-match a FRESH generation from
    `config_path`. Returns a list of human-readable drift descriptions; empty list == no drift.

    This is the anti-drift guard: `write_resources` is never called, so nothing is mutated. Three
    ways a committed tree can drift from the single source of truth are all reported —
      - a committed file whose bytes differ from the freshly generated content (stale/hand-edited),
      - an expected file that is missing from the committed tree,
      - a committed .yml that no config row generates (orphan/leftover).
    """
    expected = {fn: _dump(fragment) for fn, fragment in build_bundle_fragments(load_tables(config_path)).items()}
    resources = Path(resources_dir)
    committed = {p.name: p for p in resources.glob("*.yml")}

    problems: list[str] = []
    for fn, content in expected.items():
        if fn not in committed:
            problems.append(f"missing committed resource: {fn} (expected from config, not present)")
        elif committed[fn].read_text() != content:
            problems.append(f"drift in {fn}: committed bytes differ from fresh generation")
    for fn in committed:
        if fn not in expected:
            problems.append(f"unexpected committed resource: {fn} (no config row generates it)")
    return problems


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--config",
        default=str(repo_root / "config" / "tables.json"),
        help="Path to the single-source-of-truth tables.json (default: repo config/tables.json).",
    )
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent / "resources"),
        help="Output directory for generated bundle resource YAML (default: dabs/resources).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify-only: confirm the committed resources in --out byte-match a fresh generation "
             "from --config, exit non-zero on any drift. Writes nothing (for CI / the offline gate).",
    )
    args = parser.parse_args(argv)

    if args.check:
        problems = check_drift(args.config, args.out)
        if problems:
            for p in problems:
                print(f"DRIFT: {p}", file=sys.stderr)
            print(
                f"ERROR: committed resources in {args.out} are stale vs {args.config} "
                f"({len(problems)} issue(s)). Re-run codegen and commit dabs/resources/*.yml.",
                file=sys.stderr,
            )
            return 1
        print(f"no drift: committed resources in {args.out} match a fresh generation from {args.config}")
        return 0

    tables = load_tables(args.config)
    written = write_resources(tables, args.out)
    for path in written:
        print(f"wrote {path}")
    print(f"generated {len(written)} file(s) for {len(tables)} table(s) from {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
