"""Codegen: config/tables.json -> Databricks Asset Bundle resource YAML (ticket 01).

The DABs path is driven by the SAME single source of truth as Terraform's `for_each` and the
deploy loop (ADR 0004): the repo-root `config/tables.json`. DABs YAML cannot loop a JSON list
into N resources, so this generator emits, per table, one `postgres_synced_tables` and one
`postgres_roles` resource — a transparent, diffable artifact rather than a hidden mutator
(ADR 0006 / D2/D3). Adding a table stays a one-line `config/tables.json` edit.

Schema mapping (field names verified against `databricks bundle schema`, CLI v1.14.1):

  config/tables.json field    -> bundle location
  --------------------------      -----------------
  name                        -> resource key for both the synced table and the role
  synced_table_id             -> postgres_synced_tables.<name>.synced_table_id   (required)
  source_table_full_name      -> postgres_synced_tables.<name>.source_table_full_name
  primary_key_columns         -> postgres_synced_tables.<name>.primary_key_columns
  app_role                    -> postgres_roles.<name>.postgres_role  (the PG role name)
                                 postgres_roles.<name>.role_id        (RFC-1123 slug of app_role)
  app_schema, index_columns   -> variables.migration_targets.default[]  (see note)

Both `postgres_synced_tables` and `postgres_roles` declare `additionalProperties: false` in the
bundle schema, so there is NO native resource field for a synced table's index columns or its
target schema. Those are consumed by the Alembic migration job (which applies the indexes and the
consumer view), so they are carried as a bundle `variables` complex default (`migration_targets`)
— a bundle-legal location that `databricks bundle validate` accepts and the job task can read.
This keeps index columns "carried through" in full (no fixed-count truncation) without inventing
a resource field that the CLI would reject.

Environment-specific placement is left as bundle variable references so no customer/workspace-specific
value is committed: the role's `parent` (the Lakebase branch it lives on) uses `${var.lakebase_branch}`,
and the synced table's `postgres_database` uses `${var.lakebase_database}`. (The synced table places via
`postgres_database` only — it carries no branch reference.) Those variables are declared in the bundle's
`databricks.yml` targets (ticket 02).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

# Bundle variable references for environment-specific values (declared in databricks.yml targets).
# Kept as references — never literal workspace/branch values — so nothing customer-specific is committed.
BRANCH_VAR = "${var.lakebase_branch}"
DATABASE_VAR = "${var.lakebase_database}"

_GENERATED_HEADER = (
    "# GENERATED by dabs/generate_resources.py from config/tables.json — DO NOT EDIT BY HAND.\n"
    "# Re-run the generator after editing config/tables.json (single source of truth, ADR 0004).\n"
)


def load_tables(config_path: str | Path) -> list[dict]:
    """Read the single-source-of-truth tables config as a list of dicts."""
    with Path(config_path).open() as fh:
        tables = json.load(fh)
    if not isinstance(tables, list):
        raise ValueError(f"{config_path}: expected a JSON array of table objects")
    return tables


def _role_id(app_role: str) -> str:
    """RFC-1123 slug for the role resource id: lowercase, digits and hyphens only.

    The bundle `role_id` must match RFC 1123 (no underscores); the actual Postgres role name
    (`postgres_role`) keeps the config's `app_role` verbatim.
    """
    slug = re.sub(r"[^a-z0-9-]+", "-", app_role.lower()).strip("-")
    return slug or "app-role"


def build_synced_table_resource(table: dict) -> dict[str, Any]:
    """One `postgres_synced_tables` resource body for a table row."""
    return {
        "synced_table_id": table["synced_table_id"],
        "source_table_full_name": table["source_table_full_name"],
        "primary_key_columns": list(table["primary_key_columns"]),
        "postgres_database": DATABASE_VAR,
        "create_database_objects_if_missing": True,
    }


def build_role_resource(table: dict) -> dict[str, Any]:
    """One `postgres_roles` resource body for a table row (read-only app role)."""
    return {
        "role_id": _role_id(table["app_role"]),
        "postgres_role": table["app_role"],
        "parent": BRANCH_VAR,
    }


def build_migration_target(table: dict) -> dict[str, Any]:
    """Per-table migration metadata the Alembic job consumes (schema + full index column list)."""
    return {
        "name": table["name"],
        "app_schema": table["app_schema"],
        "app_role": table["app_role"],
        "index_columns": list(table["index_columns"]),
    }


def build_bundle_fragments(tables: list[dict]) -> dict[str, dict]:
    """Pure function: tables list -> {filename: bundle-fragment dict}.

    Emits one per-table resource file (`<name>.yml`) carrying that table's synced table and role,
    plus a single `migration_targets.yml` carrying the per-table migration metadata as a bundle
    complex variable. Fully deterministic — no timestamps or ids — so re-running is a clean diff.
    """
    fragments: dict[str, dict] = {}
    targets: list[dict] = []
    for table in tables:
        name = table["name"]
        fragments[f"{name}.yml"] = {
            "resources": {
                "postgres_synced_tables": {name: build_synced_table_resource(table)},
                "postgres_roles": {name: build_role_resource(table)},
            }
        }
        targets.append(build_migration_target(table))

    fragments["migration_targets.yml"] = {
        "variables": {
            "migration_targets": {
                "type": "complex",
                "description": (
                    "Per-table migration metadata (target schema + index columns) generated from "
                    "config/tables.json and consumed by the Alembic migration job. Index columns "
                    "have no native postgres_synced_tables field, so they are carried here."
                ),
                "default": targets,
            }
        }
    }
    return fragments


def _dump(fragment: dict) -> str:
    """Serialize a bundle fragment to deterministic, block-style YAML with a generated header."""
    body = yaml.safe_dump(fragment, default_flow_style=False, sort_keys=False)
    return _GENERATED_HEADER + body


def write_resources(tables: list[dict], out_dir: str | Path) -> list[Path]:
    """Generate and write all bundle-fragment files to `out_dir`. Returns the paths written."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, fragment in build_bundle_fragments(tables).items():
        path = out / filename
        path.write_text(_dump(fragment))
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--config",
        default=str(repo_root / "config" / "tables.json"),
        help="Path to the single-source-of-truth tables.json (default: repo config/tables.json).",
    )
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent / "resources"),
        help="Output directory for generated bundle resource YAML (default: dabs/resources).",
    )
    args = parser.parse_args(argv)

    tables = load_tables(args.config)
    written = write_resources(tables, args.out)
    for path in written:
        print(f"wrote {path}")
    print(f"generated {len(written)} file(s) for {len(tables)} table(s) from {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
